### ISSUE TITLE
Access deined for API 

### ISSUE THREAD

**Issue by kunall17** [bybit-exchange/pybit#11]
```
Python 3.7.13 (default, Mar 16 2022, 21:15:28) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pybit import usdt_perpetual
>>> API_KEY = "I0q5hohm2cp4wkeccf"
>>> API_SECRET = "VO3kERin4RyEqWPolGgf8XChRk2TKXZtkGwp"
>>> IS_TEST = True #set to True if you  are using testnet
>>> 
>>> session = usdt_perpetual.HTTP(
...     endpoint='https://api.bybit.com', 
...     api_key=API_KEY,
...     api_secret=API_SECRET
... )
>>> 
>>> session.place_active_order(
...     position_idx=1,
...     symbol="BTCUSDT",
...     side="Buy",
...     order_type="Market",
...     qty=0.004,
...     time_in_force="GoodTillCancel",
...     reduce_only=False,
...     close_on_trigger=False
... )
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/app/.heroku/python/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/app/.heroku/python/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/app/.heroku/python/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/pybit/_http_manager.py", line 259, in _submit_request
    s_json = s.json()
  File "/app/.heroku/python/lib/python3.7/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;api&#46;bybit&#46;com&#47;private&#47;linear&#47;order&#47;create" on this server.<P>
Reference&#32;&#35;18&#46;df4fde17&#46;1649587484&#46;3877d12d
</BODY>
</HTML>
: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/app/.heroku/python/lib/python3.7/site-packages/pybit/usdt_perpetual.py", line 142, in place_active_order
    auth=True
  File "/app/.heroku/python/lib/python3.7/site-packages/pybit/_http_manager.py", line 272, in _submit_request
    time=dt.utcnow().strftime("%H:%M:%S")
pybit.exceptions.FailedRequestError: Conflict. could not decode json. (ErrCode: 409) (ErrTime: 10:44:44).
Request → POST https://api.bybit.com/private/linear/order/create: {'api_key': 'I0q5hohm2cp4wkeccf', 'close_on_trigger': False, 'order_type': 'Market', 'position_idx': 1, 'qty': 0.004, 'recv_window': 5000, 'reduce_only': False, 'side': 'Buy', 'symbol': 'BTCUSDT', 'time_in_force': 'GoodTillCancel', 'timestamp': 1649587484932, 'sign': '618b588c8887a794f591fed3fee1388b0ddcb9d2934d1eb34c542851835078eb'}.
>>> 
```

**Comment by dextertd** [comment]
HTTP 403 Access Denied indicates an IP ban and is not to do with pybit. pybit doesn't have any code to handle [Bybit API's IP rate limits](https://bybit-exchange.github.io/docs/inverse/#t-ipratelimits). Although pybit should raise a more clear error, will make a note to add that.
