### ISSUE TITLE
pybit.exceptions.FailedRequestError: Http status code is not 200. (ErrCode: 401) (ErrTime: 10:26:45).

### ISSUE THREAD

**Issue by GitTattyBag** [bybit-exchange/pybit#130]
Getting this error when trying to run this python code:

    category='inverse'

    session = HTTP(
        testnet=True,
        api_key=data['api_key'],
        api_secret=data['api_secret'],
    )

    print(session.get_open_orders(
        category=category,
    ))

==========================

2023-04-20 10:26:45,769: Exception on /webhook [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/stevepa/flask_app.py", line 102, in hello_world
    print(session.get_open_orders(
  File "/home/stevepa/.local/lib/python3.10/site-packages/pybit/_v5_trade.py", line 84, in get_open_orders
    return self._submit_request(
  File "/home/stevepa/.local/lib/python3.10/site-packages/pybit/_http_manager.py", line 268, in _submit_request
    raise FailedRequestError(
pybit.exceptions.FailedRequestError: Http status code is not 200. (ErrCode: 401) (ErrTime: 10:26:45).
Request → GET https://api-testnet.bybit.com/v5/order/realtime: category=inverse.

============================================================
ByBit says this:

401: You are using v1/v2 way to pass authentication params:

GET https://api.bybit.com/v5/position/list?api_key=xxx&category=linear&recv_window=5000&symbol=ETHUSDT&timestamp=1675929695887&sign=xxx

You should pass them in the request header:

Host: api-testnet.bybit.com
-H 'X-BAPI-SIGN: XXXXXXXXXX' \
-H 'X-BAPI-API-KEY: XXXXXXXXXX' \
-H 'X-BAPI-TIMESTAMP: 1658384431891' \
-H 'X-BAPI-RECV-WINDOW: 5000'

==============================================================

Tried debugging pybit but can't seem to get it to work.

Any ideas?

**Comment by dextertd** [comment]
I cannot reproduce the issue, I get a successful response on 5.2.0. I passed `log_requests=True` and got these logs which show pybit using the correct authentication method.
```
2023-04-24 17:32:29,295 DEBUG Initializing HTTP session.
2023-04-24 17:32:29,296 DEBUG Request -> GET https://api-testnet.bybit.com/v5/order/realtime. Body: category=linear&symbol=ETHUSDT. Headers: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'cBYjudNfjwjCJXMPi5', 'X-BAPI-SIGN': '8c4181e3000d3e82354c68f5f382f27929070bb8998127c2193b935fa11175a5', 'X-BAPI-SIGN-TYPE': '2', 'X-BAPI-TIMESTAMP': '1682353949296', 'X-BAPI-RECV-WINDOW': '5000'}
2023-04-24 17:32:29,305 DEBUG Starting new HTTPS connection (1): api-testnet.bybit.com:443
2023-04-24 17:32:29,618 DEBUG https://api-testnet.bybit.com:443 "GET /v5/order/realtime?category=linear&symbol=ETHUSDT HTTP/1.1" 200 125
```

**Comment by sssyrbu** [comment]
did you solve it? i’m having the same issue

**Comment by andreas778** [comment]
same problem, I have python 3.9.1

**Comment by GitTattyBag** [comment]
Haven't tried it yet. Haven't had a chance to look at it yet

**Comment by dextertd** [comment]
What pybit version are you guys using? I cannot reproduce on 5.2.0. Please try 5.2.0 and pass `log_requests=True` and share the results.

**Comment by GitTattyBag** [comment]
Ok, looks like I had an older version of pybit. I've now got 5.2.0
installed:

[image: image.png]

However I now get this error "You have breached the ip rate limit.
(ErrCode: 403)"

2023-05-10 10:57:20,513: Exception on /webhook [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/stevepa/flask_app.py", line 108, in hello_world
    print(session.get_open_orders(
  File "/home/stevepa/.local/lib/python3.10/site-packages/pybit/_v5_trade.py",
line 84, in get_open_orders
    return self._submit_request(
  File "/home/stevepa/.local/lib/python3.10/site-packages/pybit/_http_manager.py",
line 270, in _submit_request
    raise FailedRequestError(*pybit.exceptions.FailedRequestError: You
have breached the ip rate limit. (ErrCode: 403) (ErrTime: 10:57:20).*
Request → GET https://api-testnet.bybit.com/v5/order/realtime: category=inverse.


Not sure what I am doing wrong here. Here is my code:

# A very simple Flask Hello World app for you to get started with...
from flask import Flask, request
from pybit.unified_trading import HTTP
import json
import os
import time

os.environ["ZA"] = "Africa/Johannesburg"
time.tzset()

app = Flask(__name__)

#symbol to be traded
symbol='BTCUSD'
category='inverse'


@app.route('/webhook', methods=['POST', 'GET'])
def hello_world():

    session = HTTP(
        testnet=True,
        log_requests=True,
        api_key=data['api_key'],
        api_secret=data['api_secret'],
    )

    print(session.get_open_orders(
        category=category,
    ))

    print(data['ticker'])
    print(data['bar'])
    print(data['exchange'])

    msg = "Hello W00000000000000000000000orld"
    return msg


I see you did a fix for this and added the change 2 weeks ago

[image: image.png]

but your code change is there in my
"/home/stevepa/.local/lib/python3.10/site-packages/pybit" directory:

[image: image.png]

Maybe the error is timezone related but have set it as per here:
https://help.pythonanywhere.com/pages/SettingTheTimezone

I'm Running python 3.10

Any ideas?

Thanks

Steve

**Comment by GitTattyBag** [comment]
Hi

I managed to change the timezone and it's now showing my timezone, UTC+2
correctly on the bash shell, which is great.

[image: image.png]

The app itself is still however giving an IP rate limit error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/stevepa/flask_app.py", line 108, in hello_world
    print(session.get_open_orders(
  File "/home/stevepa/.local/lib/python3.10/site-packages/pybit/_v5_trade.py",
line 84, in get_open_orders
    return self._submit_request(
  File "/home/stevepa/.local/lib/python3.10/site-packages/pybit/_http_manager.py",
line 270, in _submit_request
    raise FailedRequestError(*pybit.exceptions.FailedRequestError: You
have breached the ip rate limit. (ErrCode: 403) (ErrTime: 07:20:10).*
Request → GET https://api-testnet.bybit.com/v5/order/realtime: category=inverse.


Please can you check on your side if my IP has been blocked and unblock it
please, based on the above, that testing was mistakenly done in the
incorrect timezone.

Thanks
Steve

**Comment by GitTattyBag** [comment]
Hi

I moved over to the "eu.pythonanywhere.com" EU server and copied the files
over.

However, I am now getting this *Http status code is not 200* error again.

Request → GET https://api-testnet.bybit.com/v5/order/realtime: category=inverse.
2023-05-17 12:55:57,248: Exception on /webhook [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line
1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/stevepaEU/./flask_app.py", line 108, in hello_world
    print(session.get_open_orders(
  File "/home/stevepaEU/.local/lib/python3.10/site-packages/pybit/_v5_trade.py",
line 84, in get_open_orders
    return self._submit_request(
  File "/home/stevepaEU/.local/lib/python3.10/site-packages/pybit/_http_manager.py",
line 268, in _submit_request
    raise FailedRequestError(
pybit.exceptions.FailedRequestError: *Http status code is not 200.*
(ErrCode: 401) (ErrTime: 10:55:57).
Request → GET https://api-testnet.bybit.com/v5/order/realtime: category=inverse.

The last time, I just re-installed to pybit 5.2.0 and it fixed the
problem. Did that now and restarted the web app but the same problem:

[image: image.png]

[image: image.png]

Any ideas?

Thanks

**Comment by aidonchuk** [comment]
The same problem, Testnet python 3.11, pybit 5.6.0

pybit.exceptions.FailedRequestError: Http status code is not 200. (ErrCode: 404) (ErrTime: 15:35:00).
Request → GET https://api-testnet.bybit.com/v5/position/list: accountType=UNIFIED.

**Comment by dextertd** [comment]
Can you pass `log_requests=True` and share the .log file please? I am still unable to reproduce it.

**Comment by GitTattyBag** [comment]
i came right here thanks
