### ISSUE TITLE
Network error on Ubuntu

### ISSUE THREAD

**Issue by hugo-mrc** [bybit-exchange/pybit#136]
Hello everyone, 

After developing on Windows, I have trouble deploying in production on my Linux machine.

While running this simple class I encountered first a timeout error [Errno 110], then an OSerror [Errno 113] No route to host:

```
class Bybit():
    def __init__(self):
        print("Connecting exchange ...")
        self.session = HTTP(
            testnet=True,
            api_key="...",
            api_secret="...",
        )

        self.ws = WebSocket(
            testnet=True,
            channel_type="linear",
            api_key="...",
            api_secret="...",
            trace_logging=False,
        )
```

Has anybody encountered the same error? 
Thanks

**Comment by hugo-mrc** [comment]
Complete error:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/pybit/_websocket_stream.py", line 146, in <lambda>
    target=lambda: self.ws.run_forever(
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_app.py", line 483, in run_forever
    setSock()
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_app.py", line 413, in setSock
    handleDisconnect(e, reconnecting)
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_app.py", line 464, in handleDisconnect
    self._callback(self.on_error, e)
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_app.py", line 527, in _callback
    self.on_error(self, e)
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/pybit/_websocket_stream.py", line 140, in <lambda>
    on_error=lambda ws, err: self._on_error(err),
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/pybit/_websocket_stream.py", line 216, in _on_error
    raise error
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_app.py", line 522, in _callback
    callback(self, *args)
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/pybit/_websocket_stream.py", line 140, in <lambda>
    on_error=lambda ws, err: self._on_error(err),
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/pybit/_websocket_stream.py", line 216, in _on_error
    raise error
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_app.py", line 395, in setSock
    self.sock.connect(
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_http.py", line 197, in _open_socket
    raise error
  File "/home/hugo/Documents/blackstone_prod/venv_prod/lib/python3.8/site-packages/websocket/_http.py", line 185, in _open_socket
    sock.connect(address)
OSError: [Errno 113] No route to host

**Comment by dextertd** [comment]
I doubt this issue is exclusive to pybit. Are you able to create any websocket connections to any other address from this machine?

**Comment by hugo-mrc** [comment]
You are right, it's indeed coming from the system
Though, how can I troubleshoot that? 

I can already see that the connection working on another machine connected in the same local network AND that the connection work when I try to connect my machine through another router (eg. smartphone hotspot)

Any idea ? 
Many thanks

**Comment by dextertd** [comment]
As the problem is not related to pybit, I will close this issue, and recommend that you search for the answer in another place as I am not the best person to help diagnose it.

Thank you.
