### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by anri217** [bybit-exchange/pybit#181]
Hi! When I have open a websocket connection I have had the issue:
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/slow_fast_ema_strategy/./main.py", line 11, in <module>
    import utils.restart_service
  File "/slow_fast_ema_strategy/./utils/restart_service.py", line 9, in <module>
    from strategy_kernel.bybit.kernel import TradeKernel as BybitKernel
  File "/slow_fast_ema_strategy/./strategy_kernel/bybit/kernel.py", line 10, in <module>
    from pybit.unified_trading import WebSocket
  File "/usr/local/lib/python3.8/site-packages/pybit/unified_trading.py", line 7, in <module>
    from ._v5_misc import MiscHTTP
  File "/usr/local/lib/python3.8/site-packages/pybit/_v5_misc.py", line 1, in <module>
    from ._http_manager import _V5HTTPManager
  File "/usr/local/lib/python3.8/site-packages/pybit/_http_manager.py", line 57, in <module>
    class _V5HTTPManager:
  File "/usr/local/lib/python3.8/site-packages/pybit/_http_manager.py", line 68, in _V5HTTPManager
    retry_codes: defaultdict[dict] = field(
TypeError: 'type' object is not subscriptable
```

Could u help me?

I use python:3.9.17-slim-buster this official python image from docker hub.

**Comment by anri217** [comment]
@dextertd pls help

**Comment by beugelpp** [comment]
I have the same issue, since a few days..

**Comment by Stargazer32584** [comment]
Me too. Updated the pybit libary and Python version from 3.10.0 to 3.12. After this, i have the same problems.

**Comment by anri217** [comment]
Resolved. Use another docker image python:3.10.13-slim-bullseye. Pybit version 5.6.2.
