### ISSUE TITLE
Type hint in '_http_manager.py' causing TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by LeeFuuChang** [bybit-exchange/pybit#259]
# Minium code to replicate the error
```python
from pybit.unified_trading import HTTP
```

# Traceback
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pybit.unified_trading import HTTP
  File "...\env\lib\site-packages\pybit\unified_trading.py", line 7, in <module>
    from ._v5_misc import MiscHTTP
  File "...\env\lib\site-packages\pybit\_v5_misc.py", line 1, in <module>
    from ._http_manager import _V5HTTPManager
  File "...\env\lib\site-packages\pybit\_http_manager.py", line 62, in <module>
    class _V5HTTPManager:
  File "...\env\lib\site-packages\pybit\_http_manager.py", line 75, in _V5HTTPManager
    retry_codes: defaultdict[dict] = field(
TypeError: 'type' object is not subscriptable
```

# Fixes
### line 1
```python
from collections import defaultdict # old

from typing import DefaultDict, Any # new
```
### line 75
```python
    retry_codes: defaultdict[dict] = field( # old

    retry_codes: DefaultDict[dict, Any] = field( # new
```

**Comment by dextertd** [comment]
I can't reproduce this. What version of python are you using?

**Comment by LeeFuuChang** [comment]
> I can't reproduce this. What version of python are you using?

I'm using Python 3.8.9, on Windows.

Here's the full reproduce steps, starting from a empty direction and a new virtual-environment:

```cmd
(env) C:\Users\TUF\Desktop\test>dir   
 磁碟區 C 中的磁碟是 OS
 磁碟區序號:  4E35-07F2

 C:\Users\TUF\Desktop\test 的目錄

2025/01/28  下午 11:56    <DIR>          .
2025/01/28  下午 11:53    <DIR>          ..
2025/01/28  下午 11:56    <DIR>          env
               0 個檔案               0 位元組
               3 個目錄  313,654,104,064 位元組可用

(env) C:\Users\TUF\Desktop\test>python -V
Python 3.8.9

(env) C:\Users\TUF\Desktop\test>pip install --upgrade pip
Collecting pip
  Using cached pip-25.0-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] 存取被拒。: 'C:\\Users\\TUF\\AppData\\Local\\Temp\\pip-uninstall-mnzv1ce3\\pip.exe'
Consider using the `--user` option or check the permissions.


(env) C:\Users\TUF\Desktop\test>pip -V
pip 25.0 from c:\users\tuf\desktop\test\env\lib\site-packages\pip (python 3.8)

(env) C:\Users\TUF\Desktop\test>pip install pybit
Collecting pybit
  Downloading pybit-5.9.0.tar.gz (44 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests (from pybit)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting websocket-client (from pybit)
  Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Collecting pycryptodome (from pybit)
  Downloading pycryptodome-3.21.0-cp36-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting charset-normalizer<4,>=2 (from requests->pybit)
  Downloading charset_normalizer-3.4.1-cp38-cp38-win_amd64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests->pybit)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->pybit)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->pybit)
  Downloading certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Downloading pycryptodome-3.21.0-cp36-abi3-win_amd64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 4.7 MB/s eta 0:00:00
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
Downloading certifi-2024.12.14-py3-none-any.whl (164 kB)
Downloading charset_normalizer-3.4.1-cp38-cp38-win_amd64.whl (102 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Building wheels for collected packages: pybit
  Building wheel for pybit (pyproject.toml) ... done
  Created wheel for pybit: filename=pybit-5.9.0-py2.py3-none-any.whl size=39511 sha256=ddaff1e90ae48d9f4e9b3a1bb847a35bd7e77be8728656b314ece3f0fa3e0781
  Stored in directory: c:\users\tuf\appdata\local\pip\cache\wheels\84\cc\d9\796216173f82f56a4e7c3b3ceea6139651671425fc5d9d7800
Successfully built pybit
Installing collected packages: websocket-client, urllib3, pycryptodome, idna, charset-normalizer, certifi, requests, pybit
Successfully installed certifi-2024.12.14 charset-normalizer-3.4.1 idna-3.10 pybit-5.9.0 pycryptodome-3.21.0 requests-2.32.3 urllib3-2.2.3 websocket-client-1.8.0

(env) C:\Users\TUF\Desktop\test>python
Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pybit.unified_trading import HTTP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\TUF\Desktop\test\env\lib\site-packages\pybit\unified_trading.py", line 7, in <module>
    from ._v5_misc import MiscHTTP
  File "C:\Users\TUF\Desktop\test\env\lib\site-packages\pybit\_v5_misc.py", line 1, in <module>
    from ._http_manager import _V5HTTPManager
  File "C:\Users\TUF\Desktop\test\env\lib\site-packages\pybit\_http_manager.py", line 62, in <module>
    class _V5HTTPManager:
  File "C:\Users\TUF\Desktop\test\env\lib\site-packages\pybit\_http_manager.py", line 75, in _V5HTTPManager
    retry_codes: defaultdict[dict] = field(
TypeError: 'type' object is not subscriptable
>>>
```

**Comment by dextertd** [comment]
Thanks, I was able to reproduce this, although I'm not sure why this is happening. I did a fresh install of python3.10 in the same way as I fresh installed 3.8.9 using your instructions and can't reproduce it on 3.10.

I'll focus on bringing support to later versions instead. It's better to use a later version.
