### ISSUE TITLE
When trying to create an HTTP connection: requests.exceptions.SSLError: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url

### ISSUE THREAD

**Issue by anonavatar** [bybit-exchange/pybit#263]
Hi all,

I seem to have a rather silly problem. After creating a system generated API key via the bybit API managing system, I am trying to connect to bybit, to no avail.
API key has read-only rights and has access to Unified Trading.

My code is extremely basic, and is as follows:

> from pybit.unified_trading import HTTP
> 
> API_KEY = # MY API KEY HERE
> API_SECRET = # MY API SECRET HERE
> 
> session = HTTP(
>     api_key=API_KEY,
>     api_secret=API_SECRET,
> )

This code yields the following error:

> File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
>     conn.connect()
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\connection.py", line 741, in connect
>     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
>     ssl_sock = ssl_wrap_socket(
>                ^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 455, in wrap_socket
>     return self.sslsocket_class._create(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1042, in _create
>     self.do_handshake()
>   File "C:\Users\usr\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1320, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
>     response = self._make_request(
>                ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
>     raise new_e
> urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
>     retries = retries.increment(
>               ^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
>     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/orderbook?category=linear&symbol=BTCUSDT (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\usr\PycharmProjects\ProjectName\main.py", line 12, in <module>
>     session.get_orderbook(category="linear", symbol="BTCUSDT")
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\pybit\_v5_market.py", line 130, in get_orderbook
>     return self._submit_request(
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\pybit\_http_manager.py", line 297, in _submit_request
>     raise e
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\pybit\_http_manager.py", line 284, in _submit_request
>     s = self.client.send(r, timeout=self.timeout)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\usr\PycharmProjects\ProjectName\.venv\Lib\site-packages\requests\adapters.py", line 698, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/orderbook?category=linear&symbol=BTCUSDT (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

The API key and secret are 100% the same as in the Bybit managing system. Despite this, the error seems to indicate some kind of verification failure.

Thank you in advance for any help or light shed on this issue.

**Comment by jarviswarren** [comment]
I have the same problem like yours

**Comment by kolya5544** [comment]
`CERTIFICATE_VERIFY_FAILED` <- make sure you don't use any SSL proxy servers or interceptors/VPNs. Make sure your system time is correct and your system time is up to date.

If nothing works, try running:
`pip install certifi`
