### ISSUE TITLE
WebSocketConnectionClosedException: socket is already closed

### ISSUE THREAD

**Issue by soheilserver** [bybit-exchange/pybit#75]
I'm trying to use pybit websocket to get kline data:

    from time import sleep
    from pybit import usdt_perpetual
    ws_linear = usdt_perpetual.WebSocket(
        test=False,
        ping_interval=30,  # the default is 30
        ping_timeout=10,  # the default is 10
        domain="bybit"  # the default is "bybit"
        )
        def handle_message(msg):
            print(msg)

        ws_linear.kline_stream(
            handle_message, "BTCUSDT", "5"
        )
        while True:
            sleep(1)
        
Traceback (most recent call last):
  File "/trader/scripts/xxx.py", line 14, in <module>
    trace_logging=True
  File "/usr/local/lib/python3.6/site-packages/pybit/inverse_perpetual.py", line 709, in __init__
    self._connect(WSS)
  File "/usr/local/lib/python3.6/site-packages/pybit/_websocket_stream.py", line 167, in _connect
    self._auth()
  File "/usr/local/lib/python3.6/site-packages/pybit/_websocket_stream.py", line 192, in _auth
    "args": [self.api_key, expires, signature]
  File "/usr/local/lib/python3.6/site-packages/websocket/_app.py", line 203, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 146, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
[root@iTrade ~]# websocket._exceptions.WebSocketConnectionClosedException: socket is already closed

what is causing this problem on Centos 7?

**Comment by Liso-cz** [comment]
Hi,
I was solving similar issue yesterday. To keep the connection open, you need to be able to ping _Bybit_ server and receive response. So try to check your firewall setting. I had to adjust (wasnt set properly) ping rule in _ip6tables_, so I added something like this:

```
ip6tables -A INPUT -p ipv6-icmp -j ACCEPT
```
Note: I think for _ByBit_ _testnet_, you need only IPv4, but for live servers you need IPv6.

Also what helped me a lot was to add parameter to _WebSocket_:

```
ws_linear = usdt_perpetual.WebSocket(
...
trace_logging=True
...
)
```

Good luck! :-)
